openapi: 3.0.3
info:
  title: Quantic Match API
  description: |-
    Quantic Match API draft specifications
  version: 1.0.11
tags:
  - name: user
    description: Operations about user
paths:
  /user/login:
    post:
      operationId: loginUser
      summary: User Login
      description: Authenticate a user by email and password
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email of the user
                password:
                  type: string
                  format: password
                  description: The password of the user
              required:
                - email
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              example:
                message: Login successful
                accessToken: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiS"
                expiresIn: 3600
                tokenType: "Bearer"
        '400':
          description: Bad request
          content:
            application/json:
              example:
                message: Email and password are required
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                message: Invalid username or password
  /user/register:
    post:
      operationId: register
      summary: User Registration
      description: Register a new user
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: The first name of the user
                last_name:
                  type: string
                  description: The last name of the user
                email:
                  type: string
                  description: The email of the user
                phone:
                  type: string
                  description: The phone number of the user
                country:
                  type: string
                  description: The country of the user
                password:
                  type: string
                  format: password
                  description: The password of the user
              required:
                - first_name
                - last_name
                - email
                - phone
                - country
                - password
      responses:
        '200':
          description: Account created
          content:
            application/json:
              example:
                message: Account created
                userId: 1234
                accessToken: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiS"
                expiresIn: 3600
                tokenType: "Bearer"
        '400':
          description: Bad request
          content:
            application/json:
              example:
                message: Email is required
  /user/recover:
    post:
      operationId: recover
      summary: User account recovery
      description: Recover a user password by account email
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email of the user
              required:
                - email
      responses:
        '200':
          description: Recovery email sent
          content:
            application/json:
              example:
                message: Recovery email sent
        '400':
          description: Bad request
          content:
            application/json:
              example:
                message: Email is required
        '404':
          description: Not found
          content:
            application/json:
              example:
                message: Account not found
  /user/updatePassword:
    post:
      operationId: updatePassword
      summary: User account update password
      description: Update an account password given a recovery code
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: number
                  description: The account id
                recovery_code:
                  type: number
                  description: The recovery code get by email
                password:
                  type: string
                  description: The new password for the account
              required:
                - user_id
                - recovery_code
                - password
      responses:
        '200':
          description: Password updated
          content:
            application/json:
              example:
                message: Password updated
                userId: 1234
                accessToken: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiS"
                expiresIn: 3600
                tokenType: "Bearer"
        '400':
          description: Bad request
          content:
            application/json:
              example:
                message: Recovery code is required
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                message: Recovery code is not correct
        '404':
          description: Not found
          content:
            application/json:
              example:
                message: Account not found
  /user/get:
    get:
      operationId: getUser
      summary: Get User Public Profile
      description: Retrieve public profile data by id
      tags:
        - user
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: number
          description: The id of the user
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              example:
                quanticSequence: 4242
                firstName: John
                profileFinished: true
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                message: Invalid id
        '404':
          description: Not Found
          content:
            application/json:
              example:
                message: User not found
        '500':
          description: Not Found
          content:
            application/json:
              example:
                message: Internal server error
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
        phone:
          type: string
          example: '12345'
      xml:
        name: user
  requestBodies:
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'